#pragma once

#define BLUE_BLOCK_POINTS 1
#define YELLOW_BLOCK_POINTS 3

#define ACCELERATION_COEF 0.4
#define EFFECT_DURATION 20000
#define ABILITY_COST 20

#define BALL_VELOCITY 4
#define MAX_BALL_VELOCITY 8
#define MIN_BALL_VELOCITY 2

#define PLATFORM_VELOCITY 4
#define PLATFORM_ANIMATION_LATENCY 10
#define PLATFOTM_WIDTH_COEF 2
#define PLATFORM_VELOCITY_COEF 2
