#pragma once

#define ACCELERATION_COEF 0.5
#define INCREASEMENT_COEF 0.4
#define EFFECT_DURATION 20000
#define ABILITY_COST 20

#define BALL_VELOCITY 1
#define BALL_VELOCITY_COEF 2

#define PLATFORM_VELOCITY 1
#define PLATFORM_ANIMATION_LATENCY 50
#define PLATFOTM_WIDTH_COEF 2
#define PLATFORM_VELOCITY_COEF 2

#define POINTS 3
#define COEF_X 0.15
#define COEF_Y 0.06
